version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'theme: jhipster-internals'
      - 'theme: dependencies'
    ignored_updates:
      - match:
          dependency_name: 'p-queue'
          # ESM only version
          version_requirement: '>=7'

  - package-ecosystem: 'npm'
    directory: '/generators/client/templates/angular/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'theme: angular'
      - 'theme: dependencies'

  - package-ecosystem: 'npm'
    directory: '/generators/common/templates/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'theme: dependencies'

  - package-ecosystem: 'npm'
    directory: '/generators/client/templates/common/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'theme: front'
      - 'theme: dependencies'

  - package-ecosystem: 'npm'
    directory: '/generators/client/templates/react/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'theme: react'
      - 'theme: dependencies'

  - package-ecosystem: 'npm'
    directory: '/generators/client/templates/vue/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'theme: vue'
      - 'theme: dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'theme: github_actions'
      - 'theme: CI builds'
