on:
    pull_request:
        types:
            - opened
            - labeled
            - reopened
        branches:
            - master

jobs:
    automerge:
        runs-on: ubuntu-latest
        if: >-
            contains(github.event.pull_request.user.login, 'dependabot') &&
            contains(github.event.pull_request.labels.*.name, 'pr: automerge')
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - uses: actions/github-script@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: ${{ github.repository_owner }},
                        repo: context.repo.repo,
                        body: '@dependabot merge'
                      })
