name: "Dependabot Automerge"

on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
        branches:
            - master

jobs:
    automerge:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot'
        steps:
            - name: 'Ask dependabot to merge'
              uses: actions/github-script@v3
              if: >-
                  contains(github.event.pull_request.labels.*.name, 'pr: automerge')
              with:
                  github-token: ${{secrets.COMMENT}}
                  script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '@dependabot merge'
                      })
            - name: 'Ask dependabot to cancel merge'
              uses: actions/github-script@v3
              if: >-
                  github.event.action == 'unlabeled' &&
                  github.event.label.name == 'pr: automerge'
              with:
                  github-token: ${{secrets.COMMENT}}
                  script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '@dependabot cancel merge'
                      })
