name: "Pull Request Labeler"
on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron:  '*/5 * * * *'

jobs:
    triage:
        runs-on: ubuntu-latest
        steps:
            - uses: mshima/labeler@v2
              if: github.repository == 'mshima/generator-jhipster' && github.ref == 'master'
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
